### ISSUE TITLE
DC offset in audio

### ISSUE THREAD

**Issue by westonlast** [ValleyBell/libvgm#102]
In both https://www.foobar2000.org/components/view/foo_gep and https://ux.getuploader.com/foobar2000/download/213 there is a DC offset in the produced audio.  Both of those are based on libvgm.

Sample files: https://smd.joshw.info/p/Phantasy%20Star%20II%20%5bPhantasy%20Star%20II%20-%20Kaerazaru%20Toki%20no%20Owari%20ni%5d%20(1989-03-21)(Sega%20Development%20Division%20%233)(Sega)%5bSMD%5d.7z

This DC offset makes my DAC mute its output.

**Comment by ValleyBell** [comment]
No, they are not based on libvgm.  
They are based on VGMPlay 0.40.9, which is the version just *before* libvgm was created.

VGMPlay 0.50 and later are libvgm-based. Please check whether or not the issue happens with VGMPlay 0.51.0.
Please also tell me what sound cores are used for emulating the YM2612 and SEGA VDP PSG.

**Comment by westonlast** [comment]
I highly doubt the issue is related to only certain tracks.  It's a core output level issue; most likely YM2612 core has a constant bias.  I was using the "nuked" core, but who knows, it might not even be core-related.

**Comment by ValleyBell** [comment]
I will not debug your "doubts".

You can reopen the issue if the problem persists with an up-to-date VGMPlay. So far the bug report is invalid, as VGMPlay 0.40.9 is about 4 years old and with YM2612 cores received numerous updates since then.

Also, if I ask you to give specific information and examples, you *should give me that information* if you want me to take a serious look at the issue. You will not get away by making speculations.

**Comment by djtuBIG-MaliceX** [comment]
Also foo_gep and foo_input_vgm are hugely out of date - neither of which have not been (and for foo_gep, will not be) receiving any updates up until now, nor supported by libvgm.

**Comment by westonNexben** [comment]
No reason to be an asshole about it.  You're lucky I'm reporting anything at all.  My invalid bug report is hardly an inconvenience to your lifestyle.  Learn how to treat people well.

So you don't get a DC offset in VGMPlay?  You probably haven't tested whether it does yet.  I will when I find some time.

**Comment by westonlast** [comment]
No reason to be an asshole about it. You're lucky I'm reporting anything at all. My invalid bug report is hardly an inconvenience to your lifestyle. Learn how to treat people well.

So you don't get a DC offset in VGMPlay? You probably haven't tested whether it does yet. I will when I find some time.

**Comment by DeltaRazero** [comment]
Pretty sure posting "it doesn't work how I want it to work" and subsequently not providing the information the developer needs certainly seems lile an inconvienance; it's wasting someone's already limited time on seriously wanting to fix actual problems. Learn how to treat developers well.

**Comment by westonlast** [comment]
![image](https://user-images.githubusercontent.com/9781580/190881027-a02c56b4-a112-4ba2-b74b-b90902ebb010.png)

Raw WAV log:
![image](https://user-images.githubusercontent.com/9781580/190880931-f4f49f20-2338-48e9-ae55-6a302486eeba.png)

Normalized:
![image](https://user-images.githubusercontent.com/9781580/190881041-3b87efe7-737b-4cb7-b702-e004fc8fdca4.png)

Seems to be a general problem, although maybe more prevalent with certain operators; normalized:
![image](https://user-images.githubusercontent.com/9781580/190881064-44c08de9-c2b5-4c86-8394-55d033175975.png)

**Comment by ValleyBell** [comment]
I finally found time to look at this.  
Also: Congratulations - with all the information in the issue now, it is finally a good bug report!

I'm afraid that this is actually a bug of the game's DAC driver. Here is the waveform of the DAC channel:
![08 - Restoration DAC](https://user-images.githubusercontent.com/7661755/192116516-9856a20c-75a7-48b2-ac23-5bff1d106654.png)
The DAC driver has its "null" at value 0x40 (hex, equals -50% for unsigned 8-bit PCM). Notice how the DAC snaps to the real null-sample when it changes panning to "L only" or "R only".

Now, there are few things I'd like to mention:

1. I don't consider the DC offset a libvgm bug. libvgm provides the final output of the YM2612's _digital_ stage. And in that regard, the DC offset is 100% correct. (Also, the pops when muting/unmuting certain speakers happen ingame as well - you just don't notice them as much with all the music around it.)
2. There would be a workaround for the D.C. offset, which is applying a high-pass filter. There may be an option for this eventually, but not right now.  
   here is how the DAC channel looks with a 50 Hz highpass filter applied:
![08 - Restoration DAC Highpass 50 Hz](https://user-images.githubusercontent.com/7661755/192117475-c78e2de9-7344-46e7-9adb-a9e50c248e25.png)
3. Audacity's "normalization" feature is not the best way to analyse DC offsets IMO.  
   It seems to just calculate an average of all samples in the whole song and take the arithmetic middle as the "center". Temporary positive and negative spikes can affect this and cause a DC after the "correction".  
   Just look how it butchers the hardware recording of a sine wave from one of my MIDI modules, which has definitely no DC offset due to the analog audio transfer between MIDI module and audio interface:
![MIDI_Sine](https://user-images.githubusercontent.com/7661755/192117875-9de3588a-4c2d-4d9c-a6b8-b49ca6cfc53c.png)

**Comment by westonlast** [comment]
Thanks @ValleyBell for looking into this.  Sucks that this game is buggy in this way!  I wonder how many other commercial games have similar audio bugs...

Yes I agree the player is reproducing the audio accurately.  The one true fix would be to patch the game itself.  I'm a little surprised no one else has noticed this bug in Phantasy Star II.  My expensive DAC/Amp might just be shit.

In general I don't want to apply a highpass filter, because I'd like full reproduction of all low frequencies.

Again thank you for the analysis.
