### ISSUE TITLE
use on embedded system?

### ISSUE THREAD

**Issue by deanhuff** [ValleyBell/libvgm#115]
I'm looking for a chiptune player for an app that i'm writing to run on the playdate game console.  The console has a 168MHz cpu, 16MB of ram, 4GB of flash storage.  The SDK supports Lua & C.  (more specs here: https://help.play.date/hardware/the-specs/)

do you think libvgm would be a good candidate to run on a playdate?

**Comment by ValleyBell** [comment]
I'm sure not if this will work well. This probably depends on what sort of music you want to listen to.

regarding CPU usage:

- PSG, WSG and PCM chips will probably work.
- FM emulation will probably not work, as it is generally very CPU heavy. (YM2612 emulation may work at 22 KHz? Avoid the "Nuked" cores and use EMU/MAME/GPGX cores to get a good performance.)

regarding memory usage:

- PSG, WSG and FM should be no problem.
- PCM chips can be difficult, as they may use rather large sample ROMs. (Especially NeoGeo games are known to have like 8 MB or 16 MB of sample ROMs and libvgm will allocate full memory for that.)
- libvgm is generally very generous when it comes to memory allocation.
  - It always keeps a copy of the full VGM file in memory. (This is to simplify data access and because VGMs may be gzip-compressed.)
  - The resampler allocates space for 1 second of sample data per chip by default.  
    You could easily reduce this to e.g. 0.1 second, though. see here: https://github.com/ValleyBell/libvgm/blob/079c4e737e6a73b38ae20125521d7d9eafda28e9/emu/Resampler.c#L81
  - The YM2610 has its sample ROM memory allocated *twice*. (1x for ADPCM-A, 1x for ADPCM-B)

regarding programming language support:
- The sound chip emulation is pure C, so that will be no problem.
- File playback code is currently C++. A port to pure C is planned, but I haven't started yet.

---

Summary:
- emulation of PSG and WSG chips work
- FM and PCM chips may hit the platform's limits
- The resampler will need a one-line adjustment to reduce memory usage.
- file playback code is currently C++ and also keeps a full copy of the VGM file in memory

**Comment by deanhuff** [comment]
ValleyBell, Thank you so much for this very detailed and thoughtful response.  I'd be happy if I can get GB & NES files to play back.  I am going to give it a shot, I'll let you know how it goes!
