### ISSUE TITLE
Issue with Street Fighter EX 2 Plus's Attract track

### ISSUE THREAD

**Issue by b0x-Cub3d** [ValleyBell/libvgm#119]
The song crashes within three seconds of it playing. I noticed that it recognizes a section of the file as the clock for the Mikey chip, yet it's a 1.61 VGM file.

**Comment by mmontag** [comment]
See also https://vgmrips.net/forum/viewtopic.php?t=5722

**Comment by yoyofr** [comment]
Hello, I'm currently working on having libvgm replacing vgmplay in modizer.
I've checked the issue and did fix it by adding a check in vgmplayer.cpp.
Basically the file header seems wrong and as mikey was added in v1.72 you can fix it like this:
` if ( (_fileHdr.fileVer<0x172) && (chipType==DEVID_MIKEY) ) return 0;`

**Comment by ValleyBell** [comment]
Ah, it looks like the VGM header is faulty and contains garbage data. (bytes 0xE4 to 0xFF, which is supposed to be chip clocks)
I'll have a look at where it crashes and will try to prevent libvgm from crashing, as well as fixing the VGM itself.

**Comment by ValleyBell** [comment]
fixed by 1271ab3

Cause: The garbage data causes a Mikey chip clock of 146 459 965 to be defined, which results in a 9.1 MHz chip sample rate.  
The code for downsampling the 9.1 MHz chip output to 44/48 KHz render output ended up with an overflow in one of the calculations, so it tried to render a negative amount of samples, which crashed the player.

The fix (1) changes the number size to allow for about 10 MHz of input sample rate and (2) tries to catch the overflow and do a post-correction of the result, just in case.

(in short: I basically did everything but ignore the Mikey chip clock)
