### ISSUE TITLE
Suspicious switch in DROPlayer::LoadFile

### ISSUE THREAD

**Issue by Kaens** [ValleyBell/libvgm#126]
Stumbled upon this one (added some comments for the logic):

```cpp
switch(_fileHdr.verMajor) // <- verMajor, right?
	{
	case 0:	// version 0 (DOSBox 0.62)
	case 1:	// version 1 (DOSBox 0.63)
		switch(_fileHdr.verMajor) // <- more verMajor?
		{
		case 0: // <- but why
...
```

I'd like to express concern :D Hopefully it's some stub for something.

**Comment by Kaens** [comment]
Actually I think I got it lol

**Comment by ValleyBell** [comment]
Yeah, the outer case handles the part of the header that is common between DRO v0 and v1.
The inner cases handle the slightly different header offsets. (DRO v0 lacks the version field and 1 value was resized for v1.)

DRO v0/v1 are mostly the same, which is why there is a combined case-block for them. DRO v2 is entirely different.

**Comment by kode54** [comment]
The first `case 0` above also falls through.
