### ISSUE TITLE
Detecting gzip'd files - important?

### ISSUE THREAD

**Issue by jprjr** [ValleyBell/libvgm#14]
Hi there, I noticed the FileLoader class can specify if a file is gzip'd or not, and alternates between using a `FILE` pointer and `gzFile` pointer.

The `gzopen` function (and other function using the `gzFile` pointer) can transparently open uncompressed as well as compressed files, so I think some of this module could be simplified a bit by eliminating calls to `fopen`, checking for the gzip bytes, etc, since `gzopen` will handle all of that anyway.

Only downside is you lose the ability to tell if a file was actually compressed or not, but I'm not sure if anything in the current code relies on being able to distinguish between the two.

Figured I'd ask the question: is knowing whether or not a file was compressed is important to any future plans?

**Comment by ValleyBell** [comment]
There are a few reasons for doing it the way it is:
- IIRC you can't use gzseek with SEEK_END. (I might be misremembering though.) However I want to get a proper file size (for uncompressed files), just in case the VGM log is incomplete. (EOF offset == 0)
- Manually detecting gzip allows me to read the decompressed file size from the end of the file in most cases. (getting file size, see above)
- I'd like to have an option that lets you build libvgm without zlib support. This might be useful for DRO or S98, because those are usually not compressed.

**Comment by jprjr** [comment]
Oh, I forgot about `SEEK_END` - good to know, thank you!
