### ISSUE TITLE
Would it help to make a list of goals/restrictions/ideals for this project?

### ISSUE THREAD

**Issue by jprjr** [ValleyBell/libvgm#15]
Reason I'm asking: I hacked up a quick proof-of-concept of a purely C version of the FileUtils class, and thought it'd be interesting to try making a pure C version of the vgmplayer library, as opposed to a C wrapper around the C++ library.

However, I'm not sure if something like that is inline with the goals of this project, so I thought I'd ask before embarking on it. And that raised the more general question: do you prefer this to be a C++-first kind of library or would you be open to pull requests converting parts to C?

In PR #14  you had mentioned wanting to make a version that doesn't use gzip, are you also interested in a version that, say avoids the standard library entirely (which I think is useful in embedded projects)?

**Comment by superctr** [comment]
I agree, a pure C library means less headaches when generating bindings for other languages and also less dependencies for possible embedded applications. The file formats can use regular C structures with manual vtables, if necessary. There is very light usage of STL objects and other C++ features, so I think it shouldn't be too hard.

**Comment by ValleyBell** [comment]
I initially had a pure C library in mind. I only started doing the VGM player stuff in C++, because it allowed for easier/faster prototyping.  
I planned to backport everything to pure C once all features all implemented.

So tl;dr: Pull requests for a plain C version are welcome, but not until I consider the library complete.

I'll see if I can make a list of things I want this library to do. (Though it's probably going to be "what is already there" + finishing the player stuff.)

**Comment by TheYokai** [comment]
A list would definitely be useful for those of us looking for ways to contribute to the project. I always look into the code but I'm never quite sure what needs to be done at a given point in time.

**Comment by jprjr** [comment]
Yeah, or even just a high-level goals/ideals list would be a huge help! Just knowing going to C is a goal helps a lot, now I have an idea of what kinds of things I could try working on.

**Comment by ValleyBell** [comment]
Resolved by #20
