### ISSUE TITLE
Channel dropouts when seeking in QSound VGMs

### ISSUE THREAD

**Issue by superctr** [ValleyBell/libvgm#64]
When seeking a VGM that uses QSound, the channels may drop out entirely or play with the wrong sample.

This rarely happens when seeking forwards, but almost always happens when seeking backwards. It also happens when muting/unmuting channels in `in_vgm`.

I think the most likely reason is that the busy flag (actually called ready_flag [here](https://github.com/ValleyBell/libvgm/blob/master/emu/cores/qsound_ctr.c#L222)) is ignored by the player.

In QSound, the ready flag indicates 0x80 when the chip is accepting writes, and 0 when it is busy. I think the best behavior is to have the player either "fast-forward" the emulator, or buffer writes until the chip is ready.

The Nuked FM cores may also be affected, however they have a built-in write buffer that deals with the busy flag. (for example, see [here](https://github.com/ValleyBell/libvgm/blob/master/emu/cores/nukedopm.c#L2058)).

The VGMPlay implementation of QSound also had a simple mechanism that fast-forwarded the chip if it was busy.

**Comment by ValleyBell** [comment]
As it turned out, the issue was not really the busy flag itself. (The QSound core happily ignores it and accepts commands regardless.)

The actual issue was, that when initializing/resetting the chip state, all internal values are reset.
This reset executed in the routine that renders the samples.
Thus, the VGM requests a reset, writes all commands that occour during seeking - and *then* the core is asked to render samples and nukes all values previously written.

Commit 8ca35eb6707acc29a028115e1e7487235a9a235c fixes this by enforcing a state update when reinitialization is requested.
I made it a core option, so that it can be disabled, if you want more accurate emulation.
